name: 'Publish packages'

on:
  release:
    types:
      - created

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    uses: zondax/_workflows/.github/workflows/_publish-npm.yaml@v7
    permissions:
      contents: read
      id-token: write
